version: '3.8'

services:
  web:
    build: .
    container_name: shuttle-booking
    ports:
      - "80:80"
      - "22:22"
    depends_on:
      - db
    networks:
      - lab-network

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shuttle
      MYSQL_USER: dev
      MYSQL_PASSWORD: bob123$
    volumes:
      - ./src/sql:/docker-entrypoint-initdb.d
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
