version: '3.8'

services:
  web:
    build: .
    container_name: splinter
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - lab-network

  db:
    image: mysql:5.7
    container_name: splinter-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: underemployed
      MYSQL_PASSWORD: admin1234
    volumes:
      - ./src/sql:/docker-entrypoint-initdb.d
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
