version: '3.8'

services:
  web:
    build: .
    container_name: mr-robot
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - lab-network

  db:
    image: mysql:5.7
    container_name: mr-robot-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ourdatabase
      MYSQL_USER: newuser
      MYSQL_PASSWORD: hdgjsdhgjsdhgjsdhgjsdhgljsdhgljsd
    volumes:
      - ./src/sql:/docker-entrypoint-initdb.d
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
